apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: blockchain-system
  namespace: blockchain
  description: Blockchain System
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: blockchain-api-team
  domain: blockchain-domain
